//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace stem.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class lesson
    {
        public int id { get; set; }
        public string name { get; set; }
        public string desc { get; set; }
        public Nullable<int> language_id { get; set; }
        public string image { get; set; }
        public Nullable<int> uid { get; set; }
        public Nullable<System.DateTime> ins_date { get; set; }
        public Nullable<System.DateTime> last_change_date { get; set; }
        public Nullable<int> age_min { get; set; }
        public Nullable<int> age_max { get; set; }
        public string tag { get; set; }
        public string jigou { get; set; }
        public Nullable<bool> is_xilie { get; set; }
        public Nullable<int> shop_id { get; set; }
        public string teachers { get; set; }
        public Nullable<int> num { get; set; }
        public Nullable<double> price { get; set; }
        public string content { get; set; }
        public Nullable<int> month_num { get; set; }
    }
}
