//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace stem.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int id { get; set; }
        public string orderid { get; set; }
        public string address { get; set; }
        public string shop_name { get; set; }
        public Nullable<int> shop_id { get; set; }
        public Nullable<int> uid { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> insert_time { get; set; }
        public string phone { get; set; }
        public string name { get; set; }
        public string express { get; set; }
        public string ip { get; set; }
        public string products { get; set; }
        public Nullable<System.DateTime> pay_time { get; set; }
        public Nullable<System.DateTime> use_time { get; set; }
        public string pay_type { get; set; }
        public string @params { get; set; }
        public string remarks { get; set; }
    }
}
