//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace stem.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int id { get; set; }
        public string title { get; set; }
        public string sub_title { get; set; }
        public Nullable<int> uid { get; set; }
        public Nullable<int> language_type { get; set; }
        public Nullable<System.DateTime> ins_date { get; set; }
        public Nullable<int> old_mini { get; set; }
        public Nullable<int> old_max { get; set; }
        public string image { get; set; }
        public Nullable<int> video { get; set; }
        public string pdf { get; set; }
        public string codezip { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> starttime { get; set; }
        public Nullable<System.DateTime> endtime { get; set; }
        public Nullable<bool> is_free { get; set; }
        public Nullable<int> num { get; set; }
        public Nullable<int> orderby { get; set; }
        public Nullable<int> sale_num { get; set; }
        public string spcode { get; set; }
        public Nullable<int> lessonid { get; set; }
        public string imglist { get; set; }
        public string computer_detail { get; set; }
        public string phone_detail { get; set; }
        public string guanlian_product { get; set; }
    }
}
