//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace stem.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class shop_teachers
    {
        public int id { get; set; }
        public string name { get; set; }
        public string jianjie { get; set; }
        public string avator { get; set; }
        public string type { get; set; }
        public Nullable<int> shop_id { get; set; }
        public Nullable<int> status { get; set; }
        public string card { get; set; }
        public string card1 { get; set; }
        public string phone { get; set; }
    }
}
