//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace stem.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class shop
    {
        public int id { get; set; }
        public string name { get; set; }
        public string card { get; set; }
        public Nullable<int> fuzeren_uid { get; set; }
        public Nullable<System.DateTime> ins_date { get; set; }
        public string jianjie { get; set; }
        public string logo { get; set; }
        public string banner { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<System.DateTime> change_date { get; set; }
        public Nullable<int> status { get; set; }
    }
}
