//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace stem.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class shops_banners
    {
        public int id { get; set; }
        public string image { get; set; }
        public string url { get; set; }
        public Nullable<int> orderby { get; set; }
        public int shop_id { get; set; }
        public string title { get; set; }
    }
}
