//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace stem.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class shops_teachers
    {
        public int id { get; set; }
        public int shop_id { get; set; }
        public Nullable<System.DateTime> ins_date { get; set; }
        public Nullable<System.DateTime> birth { get; set; }
        public string name { get; set; }
        public string school { get; set; }
        public string desc { get; set; }
        public Nullable<int> type { get; set; }
        public string image { get; set; }
        public string zmcard { get; set; }
    }
}
