//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace stem.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tables_common
    {
        public int id { get; set; }
        public string table_name { get; set; }
        public string name { get; set; }
        public System.DateTime ins_date { get; set; }
        public bool is_use { get; set; }
        public string is_show { get; set; }
        public Nullable<int> shunxu { get; set; }
        public Nullable<int> pre_id { get; set; }
        public string router { get; set; }
        public string icon { get; set; }
        public Nullable<int> is_year { get; set; }
        public Nullable<int> quanxian { get; set; }
    }
}
