//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace stem.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_auth
    {
        public int uid { get; set; }
        public string realname { get; set; }
        public string cardz { get; set; }
        public string cardf { get; set; }
        public Nullable<System.DateTime> ins_date { get; set; }
        public Nullable<System.DateTime> last_change_date { get; set; }
        public string phone { get; set; }
        public Nullable<int> status { get; set; }
        public string error { get; set; }
    }
}
