//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace stem.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int uid { get; set; }
        public string name { get; set; }
        public string avator { get; set; }
        public System.DateTime ins_date { get; set; }
        public Nullable<int> dept_id { get; set; }
        public Nullable<int> role_id { get; set; }
        public Nullable<System.DateTime> last_login_date { get; set; }
        public string phone { get; set; }
        public Nullable<bool> disabled { get; set; }
        public string last_login_ip { get; set; }
    }
}
